# Import Libs and DataFrames

In [1]:
import pandas as pd


df_trn = pd.read_csv("../data/dados_projeto_evasao_treino.csv")
df_tst = pd.read_csv("../data/dados_projeto_evasao_teste.csv")

# Dados iniciai

## DataFrames

### Treino

In [2]:
df_trn

,Unnamed: 0,ds_cidade_usuario,ts_primeiro_acesso,ts_ultimo_acesso,nr_dias_desde_primeiro_acesso,nr_dias_desde_ultimo_acesso,nr_atividades_sinalizadas,nr_atividades_mapeadas,nr_discussoes_forum_postadas,nr_questionarios_abandonados,...,nr_questoes_parciais,vl_desempenho_usuario,vl_media_questoes_por_dia,vl_engajamento_notas,nr_itens_avaliados,nr_itens_nao_respondidos,vl_media_notas,nr_submissoes_codigo,vl_media_submissoes_codigo,vl_submissoes_por_dias_ativos
0,1,Campinas,0,0,19612,19612,0,0,0,0,...,0,NaN,NaN,NaN,0,0,NaN,0,NaN,NaN
1,3,Campinas,0,0,19612,19612,0,0,0,0,...,0,NaN,NaN,NaN,0,0,NaN,0,NaN,NaN
2,4,Campinas,0,0,19612,19612,0,0,0,0,...,0,NaN,NaN,NaN,0,0,NaN,0,NaN,NaN
3,5,NaN,1692744534,1693928454,20,6,0,4,0,0,...,0,1.000000,NaN,NaN,1,62,1.000000,0,NaN,NaN
4,6,Campinas,0,0,19612,19612,0,0,0,0,...,0,NaN,NaN,NaN,0,0,NaN,0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,492,curitiba,1668077732,1668083176,305,305,0,0,0,0,...,0,0.767437,NaN,NaN,2,43,0.689917,0,NaN,NaN
396,493,Campinas,0,0,19612,19612,0,0,0,0,...,0,NaN,NaN,NaN,0,0,NaN,0,NaN,NaN
397,496,Campinas,1691607939,1691608000,33,33,0,0,0,0,...,0,NaN,NaN,NaN,0,0,NaN,0,NaN,NaN
398,498,Campinas,0,0,19612,19612,0,0,0,0,...,0,NaN,NaN,NaN,0,0,NaN,0,NaN,NaN
399,499,Campinas,0,0,19612,19612,0,0,0,0,...,0,NaN,NaN,NaN,0,0,NaN,0,NaN,NaN

## info

In [3]:
print(df_trn.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 37 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   Unnamed: 0                            400 non-null    int64
 1   ds_cidade_usuario                     346 non-null    object
 2   ts_primeiro_acesso                    400 non-null    int64
 3   ts_ultimo_acesso                      400 non-null    int64
 4   nr_dias_desde_primeiro_acesso         400 non-null    int64
 5   nr_dias_desde_ultimo_acesso           400 non-null    int64
 6   nr_atividades_sinalizadas             400 non-null    int64
 7   nr_atividades_mapeadas                400 non-null    int64
 8   nr_discussoes_forum_postadas          400 non-null    int64
 9   nr_questionarios_abandonados          400 non-null    int64
 10  nr_questionarios_finalizados          400 non-null    int64
 11  vl_medio_tempo_questionario           111 non-null    float64
 12  vl_medio_tempo_questionario_avaliado  107 non-null    float64
 13  vl_desempenho_questionario            27 non-null     float64
 14  nr_intervalos_uso                     209 non-null    float64
 15  nr_dias_uso                           400 non-null    int64
 16  vl_medio_atividade_diaria             209 non-null    float64
 17  vl_engajamento_usuario_por_intervalo  29 non-null     float64
 18  vl_engajamento_usuario_intradia       29 non-null     float64
 19  nr_interacoes_usuario                 400 non-null    int64
 20  nr_dias_engajamento_discussao         400 non-null    int64
 21  nr_dias_engajamento_questionario      400 non-null    int64
 22  nr_engajamento_discussao              400 non-null    int64
 23  nr_engajamento_questionario           400 non-null    int64
 24  nr_questoes_respondidas               400 non-null    int64
 25  nr_questoes_corretas                  400 non-null    int64
 26  nr_questoes_erradas                   400 non-null    int64
 27  nr_questoes_parciais                  400 non-null    int64
 28  vl_desempenho_usuario                 113 non-null    float64
 29  vl_media_questoes_por_dia             61 non-null     float64
 30  vl_engajamento_notas                  61 non-null     float64
 31  nr_itens_avaliados                    400 non-null    int64
 32  nr_itens_nao_respondidos              400 non-null    int64
 33  vl_media_notas                        113 non-null    float64
 34  nr_submissoes_codigo                  400 non-null    int64
 35  vl_media_submissoes_codigo            4 non-null      float64
 36  vl_submissoes_por_dias_ativos         8 non-null      float64
dtypes: float64(13), int64(23), object(1)
memory usage: 115.8+ KB
None

## describe

In [4]:
print(df_trn.describe())

       Unnamed: 0  ts_primeiro_acesso  ts_ultimo_acesso  \
count  400.000000        4.000000e+02      4.000000e+02
mean   248.027500        8.647958e+08      8.664560e+08
std    140.580382        8.445285e+08      8.461345e+08
min      1.000000        0.000000e+00      0.000000e+00
25%    131.500000        0.000000e+00      0.000000e+00
50%    245.500000        1.661414e+09      1.666093e+09
75%    367.250000        1.692747e+09      1.693434e+09
max    499.000000        1.694097e+09      1.694471e+09

       nr_dias_desde_primeiro_acesso  nr_dias_desde_ultimo_acesso  \
count                     400.000000                   400.000000
mean                     9602.667500                  9583.465000
std                      9774.754241                  9793.330251
min                         4.000000                     0.000000
25%                        20.000000                    12.000000
50%                       382.500000                   328.000000
75%                     19612.000000                 19612.000000
max                     19612.000000                 19612.000000

       nr_atividades_sinalizadas  nr_atividades_mapeadas  \
count                  400.00000              400.000000
mean                     0.17750                0.947500
std                      1.22464                5.036184
min                      0.00000                0.000000
25%                      0.00000                0.000000
50%                      0.00000                0.000000
75%                      0.00000                0.000000
max                     11.00000               48.000000

       nr_discussoes_forum_postadas  nr_questionarios_abandonados  \
count                    400.000000                    400.000000
mean                       0.345000                      0.035000
std                        2.840095                      0.271956
min                        0.000000                      0.000000
25%                        0.000000                      0.000000
50%                        0.000000                      0.000000
75%                        0.000000                      0.000000
max                       39.000000                      3.000000

       nr_questionarios_finalizados  ...  nr_questoes_parciais  \
count                    400.000000  ...            400.000000
mean                       1.445000  ...              0.257500
std                        4.569922  ...              1.024117
min                        0.000000  ...              0.000000
25%                        0.000000  ...              0.000000
50%                        0.000000  ...              0.000000
75%                        1.000000  ...              0.000000
max                       27.000000  ...              9.000000

       vl_desempenho_usuario  vl_media_questoes_por_dia  vl_engajamento_notas  \
count             113.000000                  61.000000             61.000000
mean                0.876987                   0.709287              0.438528
std                 0.256726                   0.883716              0.383358
min                 0.000000                   0.012800              0.008500
25%                 0.919434                   0.209200              0.117200
50%                 1.000000                   0.500000              0.312500
75%                 1.000000                   0.928600              0.666700
max                 1.000000                   5.250000              1.333300

       nr_itens_avaliados  nr_itens_nao_respondidos  vl_media_notas  \
count          400.000000                  400.0000      113.000000
mean             2.407500                   22.2125        0.875059
std              7.610272                   60.1802        0.253001
min              0.000000                    0.0000        0.000000
25%              0.000000                    0.0000        0.919389
50%              0.000000                    0.0000        1.000000
75%              1.000000                   47.2500        1.000000
max             50.000000                  716.0000        1.000000

       nr_submissoes_codigo  vl_media_submissoes_codigo  \
count            400.000000                      4.0000
mean               0.535000                      6.7143
std                4.720645                      0.0000
min                0.000000                      6.7143
25%                0.000000                      6.7143
50%                0.000000                      6.7143
75%                0.000000                      6.7143
max               47.000000                      6.7143

       vl_submissoes_por_dias_ativos
count                       8.000000
mean                       11.083350
std                         4.914363
min                         6.000000
25%                         6.750000
50%                        11.333350
75%                        15.666700
max                        15.666700

[8 rows x 36 columns]

## columns

In [5]:
print(df_trn.columns)

Index(['Unnamed: 0', 'ds_cidade_usuario', 'ts_primeiro_acesso',
       'ts_ultimo_acesso', 'nr_dias_desde_primeiro_acesso',
       'nr_dias_desde_ultimo_acesso', 'nr_atividades_sinalizadas',
       'nr_atividades_mapeadas', 'nr_discussoes_forum_postadas',
       'nr_questionarios_abandonados', 'nr_questionarios_finalizados',
       'vl_medio_tempo_questionario', 'vl_medio_tempo_questionario_avaliado',
       'vl_desempenho_questionario', 'nr_intervalos_uso', 'nr_dias_uso',
       'vl_medio_atividade_diaria', 'vl_engajamento_usuario_por_intervalo',
       'vl_engajamento_usuario_intradia', 'nr_interacoes_usuario',
       'nr_dias_engajamento_discussao', 'nr_dias_engajamento_questionario',
       'nr_engajamento_discussao', 'nr_engajamento_questionario',
       'nr_questoes_respondidas', 'nr_questoes_corretas',
       'nr_questoes_erradas', 'nr_questoes_parciais', 'vl_desempenho_usuario',
       'vl_media_questoes_por_dia', 'vl_engajamento_notas',
       'nr_itens_avaliados', 'nr_itens_nao_respondidos', 'vl_media_notas',
       'nr_submissoes_codigo', 'vl_media_submissoes_codigo',
       'vl_submissoes_por_dias_ativos'],
      dtype='object')

### Teste

In [6]:
print(df_trn.columns)

Index(['Unnamed: 0', 'ds_cidade_usuario', 'ts_primeiro_acesso',
       'ts_ultimo_acesso', 'nr_dias_desde_primeiro_acesso',
       'nr_dias_desde_ultimo_acesso', 'nr_atividades_sinalizadas',
       'nr_atividades_mapeadas', 'nr_discussoes_forum_postadas',
       'nr_questionarios_abandonados', 'nr_questionarios_finalizados',
       'vl_medio_tempo_questionario', 'vl_medio_tempo_questionario_avaliado',
       'vl_desempenho_questionario', 'nr_intervalos_uso', 'nr_dias_uso',
       'vl_medio_atividade_diaria', 'vl_engajamento_usuario_por_intervalo',
       'vl_engajamento_usuario_intradia', 'nr_interacoes_usuario',
       'nr_dias_engajamento_discussao', 'nr_dias_engajamento_questionario',
       'nr_engajamento_discussao', 'nr_engajamento_questionario',
       'nr_questoes_respondidas', 'nr_questoes_corretas',
       'nr_questoes_erradas', 'nr_questoes_parciais', 'vl_desempenho_usuario',
       'vl_media_questoes_por_dia', 'vl_engajamento_notas',
       'nr_itens_avaliados', 'nr_itens_nao_respondidos', 'vl_media_notas',
       'nr_submissoes_codigo', 'vl_media_submissoes_codigo',
       'vl_submissoes_por_dias_ativos'],
      dtype='object')

In [7]:
df_tst

,Unnamed: 0,ds_cidade_usuario,ts_primeiro_acesso,ts_ultimo_acesso,nr_dias_desde_primeiro_acesso,nr_dias_desde_ultimo_acesso,nr_atividades_sinalizadas,nr_atividades_mapeadas,nr_discussoes_forum_postadas,nr_questionarios_abandonados,...,nr_questoes_parciais,vl_desempenho_usuario,vl_media_questoes_por_dia,vl_engajamento_notas,nr_itens_avaliados,nr_itens_nao_respondidos,vl_media_notas,nr_submissoes_codigo,vl_media_submissoes_codigo,vl_submissoes_por_dias_ativos
0,361,Campinas,1693227920,1693228016,14,14,0,0,0,0,...,0,NaN,NaN,NaN,0,0,NaN,0,NaN,NaN
1,73,Holambra,1661542019,1662149939,381,374,0,14,0,0,...,0,0.133333,0.3061,0.1633,15,144,0.133333,0,NaN,NaN
2,374,Campinas,1693578285,1694298462,10,2,0,0,0,0,...,1,0.986014,0.8571,0.5714,6,57,0.984849,0,NaN,NaN
3,155,Campinas,1690827091,1690827413,42,42,0,0,0,0,...,0,NaN,NaN,NaN,0,0,NaN,0,NaN,NaN
4,104,Campinas,0,0,19612,19612,0,0,0,0,...,0,NaN,NaN,NaN,0,0,NaN,0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,347,NaN,1690662696,1690662696,44,44,0,0,0,0,...,0,NaN,NaN,NaN,0,0,NaN,0,NaN,NaN
96,86,NaN,1693428019,1694470591,12,0,0,0,0,0,...,0,1.000000,0.6667,0.6667,2,61,1.000000,0,NaN,NaN
97,75,Campinas,0,0,19612,19612,0,0,0,0,...,0,NaN,NaN,NaN,0,0,NaN,0,NaN,NaN
98,438,Campinas,0,0,19612,19612,0,0,0,0,...,0,NaN,NaN,NaN,0,0,NaN,0,NaN,NaN
99,15,Campinas,0,0,19612,19612,0,0,0,0,...,0,NaN,NaN,NaN,0,0,NaN,0,NaN,NaN

# Removendo colunas não relevantes

In [8]:
df_trn = df_trn.loc[:, ~df_trn.columns.str.contains('^Unnamed')]
df_tst = df_tst.loc[:, ~df_tst.columns.str.contains('^Unnamed')]

In [9]:
print(df_tst.isnull().sum())

ds_cidade_usuario                        15
ts_primeiro_acesso                        0
ts_ultimo_acesso                          0
nr_dias_desde_primeiro_acesso             0
nr_dias_desde_ultimo_acesso               0
nr_atividades_sinalizadas                 0
nr_atividades_mapeadas                    0
nr_discussoes_forum_postadas              0
nr_questionarios_abandonados              0
nr_questionarios_finalizados              0
vl_medio_tempo_questionario              71
vl_medio_tempo_questionario_avaliado     75
vl_desempenho_questionario               98
nr_intervalos_uso                        53
nr_dias_uso                               0
vl_medio_atividade_diaria                53
vl_engajamento_usuario_por_intervalo     93
vl_engajamento_usuario_intradia          93
nr_interacoes_usuario                     0
nr_dias_engajamento_discussao             0
nr_dias_engajamento_questionario          0
nr_engajamento_discussao                  0
nr_engajamento_questionario               0
nr_questoes_respondidas                   0
nr_questoes_corretas                      0
nr_questoes_erradas                       0
nr_questoes_parciais                      0
vl_desempenho_usuario                    71
vl_media_questoes_por_dia                84
vl_engajamento_notas                     84
nr_itens_avaliados                        0
nr_itens_nao_respondidos                  0
vl_media_notas                           71
nr_submissoes_codigo                      0
vl_media_submissoes_codigo              100
vl_submissoes_por_dias_ativos           100
dtype: int64

In [10]:
limite_nulos = len(df_trn) * 0.2
df_trn = df_trn.dropna(thresh=limite_nulos, axis=1)

limite_nulos = len(df_tst) * 0.2
df_tst = df_tst.dropna(thresh=limite_nulos, axis=1)

# Convertendo timeStamps

In [11]:
df_trn['ts_primeiro_acesso'] = pd.to_datetime(df_trn['ts_primeiro_acesso'], unit='s', errors='coerce')
df_trn['ts_ultimo_acesso'] = pd.to_datetime(df_trn['ts_ultimo_acesso'], unit='s', errors='coerce')

df_tst['ts_primeiro_acesso'] = pd.to_datetime(df_tst['ts_primeiro_acesso'], unit='s', errors='coerce')
df_tst['ts_ultimo_acesso'] = pd.to_datetime(df_tst['ts_ultimo_acesso'], unit='s', errors='coerce')

In [12]:
df_trn = df_trn.rename(columns={
    'ts_primeiro_acesso': 'dt_primeiro_acesso',
    'ts_ultimo_acesso': 'dt_ultimo_acesso'
})

df_tst = df_tst.rename(columns={
    'ts_primeiro_acesso': 'dt_primeiro_acesso',
    'ts_ultimo_acesso': 'dt_ultimo_acesso'
})

# Tratando valores faltantes

In [13]:
print(df_trn.isnull().sum())

ds_cidade_usuario                        54
dt_primeiro_acesso                        0
dt_ultimo_acesso                          0
nr_dias_desde_primeiro_acesso             0
nr_dias_desde_ultimo_acesso               0
nr_atividades_sinalizadas                 0
nr_atividades_mapeadas                    0
nr_discussoes_forum_postadas              0
nr_questionarios_abandonados              0
nr_questionarios_finalizados              0
vl_medio_tempo_questionario             289
vl_medio_tempo_questionario_avaliado    293
nr_intervalos_uso                       191
nr_dias_uso                               0
vl_medio_atividade_diaria               191
nr_interacoes_usuario                     0
nr_dias_engajamento_discussao             0
nr_dias_engajamento_questionario          0
nr_engajamento_discussao                  0
nr_engajamento_questionario               0
nr_questoes_respondidas                   0
nr_questoes_corretas                      0
nr_questoes_erradas                       0
nr_questoes_parciais                      0
vl_desempenho_usuario                   287
nr_itens_avaliados                        0
nr_itens_nao_respondidos                  0
vl_media_notas                          287
nr_submissoes_codigo                      0
dtype: int64

# Vendo melhor forma de tratar os nulos

### Observando o tipo de cada variavel

In [14]:
# lista de colunas por tipo
dt_cols  = df_trn.select_dtypes(include=['datetime64[ns]', 'datetime64[ns, UTC]']).columns.tolist()
num_cols = df_trn.select_dtypes(include=['number']).columns.tolist()
obj_cols = df_trn.select_dtypes(include=['object', 'category']).columns.tolist()

print("Datetime:",  dt_cols)
print("Numéricas:", num_cols)
print("Categóricas:", obj_cols)

Datetime: ['dt_primeiro_acesso', 'dt_ultimo_acesso']
Numéricas: ['nr_dias_desde_primeiro_acesso', 'nr_dias_desde_ultimo_acesso', 'nr_atividades_sinalizadas', 'nr_atividades_mapeadas', 'nr_discussoes_forum_postadas', 'nr_questionarios_abandonados', 'nr_questionarios_finalizados', 'vl_medio_tempo_questionario', 'vl_medio_tempo_questionario_avaliado', 'nr_intervalos_uso', 'nr_dias_uso', 'vl_medio_atividade_diaria', 'nr_interacoes_usuario', 'nr_dias_engajamento_discussao', 'nr_dias_engajamento_questionario', 'nr_engajamento_discussao', 'nr_engajamento_questionario', 'nr_questoes_respondidas', 'nr_questoes_corretas', 'nr_questoes_erradas', 'nr_questoes_parciais', 'vl_desempenho_usuario', 'nr_itens_avaliados', 'nr_itens_nao_respondidos', 'vl_media_notas', 'nr_submissoes_codigo']
Categóricas: ['ds_cidade_usuario']

### Investigar valores faltantes — antes de realizar fillna

In [15]:
print("===== DATETIME =====")
print(df_trn[dt_cols].isna().sum(), end="\n\n")

print("===== NUMÉRICAS =====")
print(df_trn[num_cols].isna().sum(), end="\n\n")

print("===== CATEGÓRICAS =====")
print(df_trn[obj_cols].isna().sum())

===== DATETIME =====
dt_primeiro_acesso    0
dt_ultimo_acesso      0
dtype: int64

===== NUMÉRICAS =====
nr_dias_desde_primeiro_acesso             0
nr_dias_desde_ultimo_acesso               0
nr_atividades_sinalizadas                 0
nr_atividades_mapeadas                    0
nr_discussoes_forum_postadas              0
nr_questionarios_abandonados              0
nr_questionarios_finalizados              0
vl_medio_tempo_questionario             289
vl_medio_tempo_questionario_avaliado    293
nr_intervalos_uso                       191
nr_dias_uso                               0
vl_medio_atividade_diaria               191
nr_interacoes_usuario                     0
nr_dias_engajamento_discussao             0
nr_dias_engajamento_questionario          0
nr_engajamento_discussao                  0
nr_engajamento_questionario               0
nr_questoes_respondidas                   0
nr_questoes_corretas                      0
nr_questoes_erradas                       0
nr_questoes_parciais                      0
vl_desempenho_usuario                   287
nr_itens_avaliados                        0
nr_itens_nao_respondidos                  0
vl_media_notas                          287
nr_submissoes_codigo                      0
dtype: int64

===== CATEGÓRICAS =====
ds_cidade_usuario    54
dtype: int64

### Avaliar porcentagem de nulos por coluna numérica

In [16]:
missing_pct = df_trn[num_cols].isna().mean() * 100
print(missing_pct.sort_values(ascending=False))

vl_medio_tempo_questionario_avaliado    73.25
vl_medio_tempo_questionario             72.25
vl_desempenho_usuario                   71.75
vl_media_notas                          71.75
nr_intervalos_uso                       47.75
vl_medio_atividade_diaria               47.75
nr_questionarios_abandonados             0.00
nr_dias_desde_primeiro_acesso            0.00
nr_dias_desde_ultimo_acesso              0.00
nr_atividades_sinalizadas                0.00
nr_questionarios_finalizados             0.00
nr_atividades_mapeadas                   0.00
nr_discussoes_forum_postadas             0.00
nr_dias_uso                              0.00
nr_dias_engajamento_questionario         0.00
nr_engajamento_discussao                 0.00
nr_interacoes_usuario                    0.00
nr_dias_engajamento_discussao            0.00
nr_questoes_respondidas                  0.00
nr_engajamento_questionario              0.00
nr_questoes_erradas                      0.00
nr_questoes_corretas                     0.00
nr_questoes_parciais                     0.00
nr_itens_avaliados                       0.00
nr_itens_nao_respondidos                 0.00
nr_submissoes_codigo                     0.00
dtype: float64

### Drop das colunas com >70% de missing

In [17]:
to_drop = [
    'vl_medio_tempo_questionario_avaliado',
    'vl_medio_tempo_questionario',
    'vl_desempenho_usuario',
    'vl_media_notas'
]
df_trn = df_trn.drop(columns=to_drop)
df_tst = df_tst.drop(columns=to_drop)

### Imputar colunas com ~47% de missing pela mediana

In [18]:
to_impute = ['nr_intervalos_uso', 'vl_medio_atividade_diaria']
medians_trn = df_trn[to_impute].median()
medians_tst = df_tst[to_impute].median()

df_trn[to_impute] = df_trn[to_impute].fillna(medians_trn)
df_tst[to_impute] = df_tst[to_impute].fillna(medians_tst)

### Verificando que não sobrou nenhum NaN

In [19]:
print(df_trn[to_impute].isna().sum())
print(df_tst[to_impute].isna().sum())

nr_intervalos_uso            0
vl_medio_atividade_diaria    0
dtype: int64
nr_intervalos_uso            0
vl_medio_atividade_diaria    0
dtype: int64

# Tratar ds_cidade_usuario Imputando Desconhecido em campos NaN

In [20]:
df_trn["ds_cidade_usuario"]

0      Campinas
1      Campinas
2      Campinas
3           NaN
4      Campinas
         ...
395    curitiba
396    Campinas
397    Campinas
398    Campinas
399    Campinas
Name: ds_cidade_usuario, Length: 400, dtype: object

In [21]:
df_trn['ds_cidade_usuario'] = df_trn['ds_cidade_usuario'].fillna('Desconhecido')
df_tst['ds_cidade_usuario'] = df_tst['ds_cidade_usuario'].fillna('Desconhecido')

### Verificando se tem algum nulo no ds_cidade_usuario

In [22]:
print(df_trn["ds_cidade_usuario"].isna().sum(), "\n")
print(df_tst["ds_cidade_usuario"].isna().sum(), "\n")

0

0

### Verifica NaNs em todas as colunas se temos NaN

In [23]:
print("Nulos em df_trn:\n", df_trn.isna().sum(), "\n")
print("Nulos em df_tst:\n", df_tst.isna().sum(), "\n")

Nulos em df_trn:
 ds_cidade_usuario                   0
dt_primeiro_acesso                  0
dt_ultimo_acesso                    0
nr_dias_desde_primeiro_acesso       0
nr_dias_desde_ultimo_acesso         0
nr_atividades_sinalizadas           0
nr_atividades_mapeadas              0
nr_discussoes_forum_postadas        0
nr_questionarios_abandonados        0
nr_questionarios_finalizados        0
nr_intervalos_uso                   0
nr_dias_uso                         0
vl_medio_atividade_diaria           0
nr_interacoes_usuario               0
nr_dias_engajamento_discussao       0
nr_dias_engajamento_questionario    0
nr_engajamento_discussao            0
nr_engajamento_questionario         0
nr_questoes_respondidas             0
nr_questoes_corretas                0
nr_questoes_erradas                 0
nr_questoes_parciais                0
nr_itens_avaliados                  0
nr_itens_nao_respondidos            0
nr_submissoes_codigo                0
dtype: int64

Nulos em df_tst:
 ds_cidade_usuario                   0
dt_primeiro_acesso                  0
dt_ultimo_acesso                    0
nr_dias_desde_primeiro_acesso       0
nr_dias_desde_ultimo_acesso         0
nr_atividades_sinalizadas           0
nr_atividades_mapeadas              0
nr_discussoes_forum_postadas        0
nr_questionarios_abandonados        0
nr_questionarios_finalizados        0
nr_intervalos_uso                   0
nr_dias_uso                         0
vl_medio_atividade_diaria           0
nr_interacoes_usuario               0
nr_dias_engajamento_discussao       0
nr_dias_engajamento_questionario    0
nr_engajamento_discussao            0
nr_engajamento_questionario         0
nr_questoes_respondidas             0
nr_questoes_corretas                0
nr_questoes_erradas                 0
nr_questoes_parciais                0
nr_itens_avaliados                  0
nr_itens_nao_respondidos            0
nr_submissoes_codigo                0
dtype: int64

### Verificando quantas linhas serão apagadas Por duplicidade

In [24]:
print("Duplicatas em treino:", df_trn.duplicated().sum())
print("Duplicatas em teste:", df_tst.duplicated().sum())

Duplicatas em treino: 307
Duplicatas em teste: 62

In [25]:
print(f"Antes: {len(df_trn)} linhas")

print(f"Antes: {len(df_tst)} linhas")

Antes: 400 linhas
Antes: 100 linhas

### Remover duplicatas, mantendo a última ocorrência

In [26]:
df_trn = df_trn.drop_duplicates(keep='last')
df_tst = df_tst.drop_duplicates(keep='last')

### Verificando se temos duplicatas ainda

In [27]:
print("Após remoção — treino:", df_trn.duplicated().sum())
print("Após remoção — teste:", df_tst.duplicated().sum())

Após remoção — treino: 0
Após remoção — teste: 0

### Verificando quantas linhas sobraram

In [28]:
print(f"Depois: {len(df_trn)} linhas")

print(f"Depois: {len(df_tst)} linhas")

Depois: 93 linhas
Depois: 38 linhas

# Ajustando data invalidadas

### Verificando quantas linhas nos datasets tem valores invalidos (1970 é o ponto inicial das bibliotecas)

In [29]:
print("df_trn - dt_primeiro_acesso == 1970:", (df_trn['dt_primeiro_acesso'].dt.year == 1970).sum())
print("df_trn - dt_ultimo_acesso   == 1970:", (df_trn['dt_ultimo_acesso'].dt.year == 1970).sum())

print("df_tst - dt_primeiro_acesso == 1970:", (df_tst['dt_primeiro_acesso'].dt.year == 1970).sum())
print("df_tst - dt_ultimo_acesso   == 1970:", (df_tst['dt_ultimo_acesso'].dt.year == 1970).sum())

df_trn - dt_primeiro_acesso == 1970: 3
df_trn - dt_ultimo_acesso   == 1970: 3
df_tst - dt_primeiro_acesso == 1970: 2
df_tst - dt_ultimo_acesso   == 1970: 2

In [30]:
df_trn = df_trn[df_trn['dt_primeiro_acesso'].dt.year != 1970]
df_trn = df_trn[df_trn['dt_ultimo_acesso'].dt.year != 1970]

df_tst = df_tst[df_tst['dt_primeiro_acesso'].dt.year != 1970]
df_tst = df_tst[df_tst['dt_ultimo_acesso'].dt.year != 1970]

# Supondo que alunos que não entram a mais de 90 dias fora do periodo de ferias abandonaram

In [31]:
meses_ferias = [1, 2, 7, 12]

def verificar_abandono(row):
    ultimo_acesso = row['dt_ultimo_acesso']
    dias_sem_acesso = row['nr_dias_desde_ultimo_acesso']

    if ultimo_acesso.month in meses_ferias:
        return 0
    elif dias_sem_acesso > 90:
        return 1
    else:
        return 0
    
df_trn['abandono'] = df_trn.apply(verificar_abandono, axis=1)
df_tst['abandono'] = df_tst.apply(verificar_abandono, axis=1)

# removendo colunas não mais nescessarias

In [32]:
colunas_remover = ['dt_primeiro_acesso', 'dt_ultimo_acesso', 'ds_cidade_usuario']
df_trn = df_trn.drop(columns=colunas_remover)
df_tst = df_tst.drop(columns=colunas_remover)

# Revisando dados

In [33]:
df_trn

,nr_dias_desde_primeiro_acesso,nr_dias_desde_ultimo_acesso,nr_atividades_sinalizadas,nr_atividades_mapeadas,nr_discussoes_forum_postadas,nr_questionarios_abandonados,nr_questionarios_finalizados,nr_intervalos_uso,nr_dias_uso,vl_medio_atividade_diaria,...,nr_engajamento_discussao,nr_engajamento_questionario,nr_questoes_respondidas,nr_questoes_corretas,nr_questoes_erradas,nr_questoes_parciais,nr_itens_avaliados,nr_itens_nao_respondidos,nr_submissoes_codigo,abandono
3,20,6,0,4,0,0,1,14.0,3,4.7333,...,1,34,44,1,0,0,1,62,0,0
7,19,18,0,0,0,0,0,1.0,2,9.5000,...,1,3,0,0,0,0,0,0,0,0
26,34,34,0,0,0,0,1,0.0,1,36.0000,...,0,24,44,1,0,0,1,62,0,0
29,20,5,0,0,0,0,2,15.0,7,11.7500,...,1,43,58,40,16,0,5,58,0,0
31,20,20,0,0,0,0,0,0.0,1,7.0000,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
391,220,12,0,12,0,0,0,208.0,3,0.1866,...,0,0,0,0,0,0,0,90,0,0
392,12,1,0,0,0,0,2,11.0,2,5.3333,...,0,48,59,39,18,0,1,62,0,0
394,4,0,0,0,0,0,4,4.0,4,70.6000,...,18,115,64,55,5,1,21,42,6,0
395,305,305,0,0,0,0,1,273.0,4,0.4051,...,0,86,37,14,10,0,2,43,0,1
397,33,33,0,0,0,0,0,0.0,1,5.0000,...,0,0,0,0,0,0,0,0,0,0

In [34]:
print(df_trn.info())

<class 'pandas.core.frame.DataFrame'>
Index: 90 entries, 3 to 397
Data columns (total 23 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   nr_dias_desde_primeiro_acesso     90 non-null     int64
 1   nr_dias_desde_ultimo_acesso       90 non-null     int64
 2   nr_atividades_sinalizadas         90 non-null     int64
 3   nr_atividades_mapeadas            90 non-null     int64
 4   nr_discussoes_forum_postadas      90 non-null     int64
 5   nr_questionarios_abandonados      90 non-null     int64
 6   nr_questionarios_finalizados      90 non-null     int64
 7   nr_intervalos_uso                 90 non-null     float64
 8   nr_dias_uso                       90 non-null     int64
 9   vl_medio_atividade_diaria         90 non-null     float64
 10  nr_interacoes_usuario             90 non-null     int64
 11  nr_dias_engajamento_discussao     90 non-null     int64
 12  nr_dias_engajamento_questionario  90 non-null     int64
 13  nr_engajamento_discussao          90 non-null     int64
 14  nr_engajamento_questionario       90 non-null     int64
 15  nr_questoes_respondidas           90 non-null     int64
 16  nr_questoes_corretas              90 non-null     int64
 17  nr_questoes_erradas               90 non-null     int64
 18  nr_questoes_parciais              90 non-null     int64
 19  nr_itens_avaliados                90 non-null     int64
 20  nr_itens_nao_respondidos          90 non-null     int64
 21  nr_submissoes_codigo              90 non-null     int64
 22  abandono                          90 non-null     int64
dtypes: float64(2), int64(21)
memory usage: 16.9 KB
None

In [35]:
df_trn

,nr_dias_desde_primeiro_acesso,nr_dias_desde_ultimo_acesso,nr_atividades_sinalizadas,nr_atividades_mapeadas,nr_discussoes_forum_postadas,nr_questionarios_abandonados,nr_questionarios_finalizados,nr_intervalos_uso,nr_dias_uso,vl_medio_atividade_diaria,...,nr_engajamento_discussao,nr_engajamento_questionario,nr_questoes_respondidas,nr_questoes_corretas,nr_questoes_erradas,nr_questoes_parciais,nr_itens_avaliados,nr_itens_nao_respondidos,nr_submissoes_codigo,abandono
3,20,6,0,4,0,0,1,14.0,3,4.7333,...,1,34,44,1,0,0,1,62,0,0
7,19,18,0,0,0,0,0,1.0,2,9.5000,...,1,3,0,0,0,0,0,0,0,0
26,34,34,0,0,0,0,1,0.0,1,36.0000,...,0,24,44,1,0,0,1,62,0,0
29,20,5,0,0,0,0,2,15.0,7,11.7500,...,1,43,58,40,16,0,5,58,0,0
31,20,20,0,0,0,0,0,0.0,1,7.0000,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
391,220,12,0,12,0,0,0,208.0,3,0.1866,...,0,0,0,0,0,0,0,90,0,0
392,12,1,0,0,0,0,2,11.0,2,5.3333,...,0,48,59,39,18,0,1,62,0,0
394,4,0,0,0,0,0,4,4.0,4,70.6000,...,18,115,64,55,5,1,21,42,6,0
395,305,305,0,0,0,0,1,273.0,4,0.4051,...,0,86,37,14,10,0,2,43,0,1
397,33,33,0,0,0,0,0,0.0,1,5.0000,...,0,0,0,0,0,0,0,0,0,0

In [36]:
print(df_trn.describe())

       nr_dias_desde_primeiro_acesso  nr_dias_desde_ultimo_acesso  \
count                      90.000000                    90.000000
mean                       81.466667                    45.233333
std                       118.896348                    85.249673
min                         4.000000                     0.000000
25%                        12.000000                     6.000000
50%                        21.000000                    13.000000
75%                        54.000000                    26.750000
max                       390.000000                   353.000000

       nr_atividades_sinalizadas  nr_atividades_mapeadas  \
count                  90.000000               90.000000
mean                    0.188889                1.855556
std                     1.271065                7.191695
min                     0.000000                0.000000
25%                     0.000000                0.000000
50%                     0.000000                0.000000
75%                     0.000000                0.000000
max                    11.000000               48.000000

       nr_discussoes_forum_postadas  nr_questionarios_abandonados  \
count                     90.000000                     90.000000
mean                       0.666667                      0.066667
std                        4.232034                      0.390908
min                        0.000000                      0.000000
25%                        0.000000                      0.000000
50%                        0.000000                      0.000000
75%                        0.000000                      0.000000
max                       39.000000                      3.000000

       nr_questionarios_finalizados  nr_intervalos_uso  nr_dias_uso  \
count                     90.000000          90.000000    90.000000
mean                       1.944444          47.744444    10.311111
std                        4.596924         100.093502    28.986492
min                        0.000000           0.000000     1.000000
25%                        0.000000           0.000000     1.000000
50%                        0.000000           4.000000     2.000000
75%                        2.000000          26.500000     4.000000
max                       27.000000         390.000000   181.000000

       vl_medio_atividade_diaria  ...  nr_engajamento_discussao  \
count                  90.000000  ...                 90.000000
mean                   16.178160  ...                 12.922222
std                    22.402759  ...                 66.738502
min                     0.170800  ...                  0.000000
25%                     4.169225  ...                  0.000000
50%                     7.114450  ...                  0.000000
75%                    16.375000  ...                  1.750000
max                   111.000000  ...                619.000000

       nr_engajamento_questionario  nr_questoes_respondidas  \
count                    90.000000                90.000000
mean                    103.688889                31.988889
std                     299.277318                57.058120
min                       0.000000                 0.000000
25%                       0.000000                 0.000000
50%                      11.500000                 0.000000
75%                      63.500000                58.000000
max                    1944.000000               345.000000

       nr_questoes_corretas  nr_questoes_erradas  nr_questoes_parciais  \
count             90.000000            90.000000             90.000000
mean              22.788889             2.866667              0.377778
std               47.422911             5.092846              1.137490
min                0.000000             0.000000              0.000000
25%                0.000000             0.000000              0.000000
50%                0.500000             0.000000              0.000000
75%               44.750000             4.750000              0.000000
max              290.000000            21.000000              9.000000

       nr_itens_avaliados  nr_itens_nao_respondidos  nr_submissoes_codigo  \
count           90.000000                 90.000000             90.000000
mean             3.233333                 41.022222              0.733333
std              7.802405                 85.029668              5.063196
min              0.000000                  0.000000              0.000000
25%              0.000000                  0.000000              0.000000
50%              0.000000                  2.000000              0.000000
75%              2.000000                 61.000000              0.000000
max             50.000000                716.000000             47.000000

        abandono
count  90.000000
mean    0.077778
std     0.269322
min     0.000000
25%     0.000000
50%     0.000000
75%     0.000000
max     1.000000

[8 rows x 23 columns]

In [37]:
print(df_trn.dtypes)

nr_dias_desde_primeiro_acesso         int64
nr_dias_desde_ultimo_acesso           int64
nr_atividades_sinalizadas             int64
nr_atividades_mapeadas                int64
nr_discussoes_forum_postadas          int64
nr_questionarios_abandonados          int64
nr_questionarios_finalizados          int64
nr_intervalos_uso                   float64
nr_dias_uso                           int64
vl_medio_atividade_diaria           float64
nr_interacoes_usuario                 int64
nr_dias_engajamento_discussao         int64
nr_dias_engajamento_questionario      int64
nr_engajamento_discussao              int64
nr_engajamento_questionario           int64
nr_questoes_respondidas               int64
nr_questoes_corretas                  int64
nr_questoes_erradas                   int64
nr_questoes_parciais                  int64
nr_itens_avaliados                    int64
nr_itens_nao_respondidos              int64
nr_submissoes_codigo                  int64
abandono                              int64
dtype: object

In [38]:
print(df_trn.isnull().sum())

nr_dias_desde_primeiro_acesso       0
nr_dias_desde_ultimo_acesso         0
nr_atividades_sinalizadas           0
nr_atividades_mapeadas              0
nr_discussoes_forum_postadas        0
nr_questionarios_abandonados        0
nr_questionarios_finalizados        0
nr_intervalos_uso                   0
nr_dias_uso                         0
vl_medio_atividade_diaria           0
nr_interacoes_usuario               0
nr_dias_engajamento_discussao       0
nr_dias_engajamento_questionario    0
nr_engajamento_discussao            0
nr_engajamento_questionario         0
nr_questoes_respondidas             0
nr_questoes_corretas                0
nr_questoes_erradas                 0
nr_questoes_parciais                0
nr_itens_avaliados                  0
nr_itens_nao_respondidos            0
nr_submissoes_codigo                0
abandono                            0
dtype: int64

# Salvando Copia dados limpos

In [39]:
df_trn.to_csv('../data/anderson_dados_limpos_treino.csv', index=False)
df_tst.to_csv('../data/anderson_dados_limpos_teste.csv', index=False)