# Import Libs and DataFrames

In [1]:
import pandas as pd


df_trn = pd.read_csv("../data/dados_projeto_evasao_treino.csv")
df_tst = pd.read_csv("../data/dados_projeto_evasao_teste.csv")

# Dados iniciai

## DataFrames

### Treino

In [2]:
df_trn

,Unnamed: 0,ds_cidade_usuario,ts_primeiro_acesso,ts_ultimo_acesso,nr_dias_desde_primeiro_acesso,nr_dias_desde_ultimo_acesso,nr_atividades_sinalizadas,nr_atividades_mapeadas,nr_discussoes_forum_postadas,nr_questionarios_abandonados,...,nr_questoes_parciais,vl_desempenho_usuario,vl_media_questoes_por_dia,vl_engajamento_notas,nr_itens_avaliados,nr_itens_nao_respondidos,vl_media_notas,nr_submissoes_codigo,vl_media_submissoes_codigo,vl_submissoes_por_dias_ativos
0,1,Campinas,0,0,19612,19612,0,0,0,0,...,0,NaN,NaN,NaN,0,0,NaN,0,NaN,NaN
1,3,Campinas,0,0,19612,19612,0,0,0,0,...,0,NaN,NaN,NaN,0,0,NaN,0,NaN,NaN
2,4,Campinas,0,0,19612,19612,0,0,0,0,...,0,NaN,NaN,NaN,0,0,NaN,0,NaN,NaN
3,5,NaN,1692744534,1693928454,20,6,0,4,0,0,...,0,1.000000,NaN,NaN,1,62,1.000000,0,NaN,NaN
4,6,Campinas,0,0,19612,19612,0,0,0,0,...,0,NaN,NaN,NaN,0,0,NaN,0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,492,curitiba,1668077732,1668083176,305,305,0,0,0,0,...,0,0.767437,NaN,NaN,2,43,0.689917,0,NaN,NaN
396,493,Campinas,0,0,19612,19612,0,0,0,0,...,0,NaN,NaN,NaN,0,0,NaN,0,NaN,NaN
397,496,Campinas,1691607939,1691608000,33,33,0,0,0,0,...,0,NaN,NaN,NaN,0,0,NaN,0,NaN,NaN
398,498,Campinas,0,0,19612,19612,0,0,0,0,...,0,NaN,NaN,NaN,0,0,NaN,0,NaN,NaN
399,499,Campinas,0,0,19612,19612,0,0,0,0,...,0,NaN,NaN,NaN,0,0,NaN,0,NaN,NaN

## info

In [3]:
print(df_trn.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 37 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   Unnamed: 0                            400 non-null    int64
 1   ds_cidade_usuario                     346 non-null    object
 2   ts_primeiro_acesso                    400 non-null    int64
 3   ts_ultimo_acesso                      400 non-null    int64
 4   nr_dias_desde_primeiro_acesso         400 non-null    int64
 5   nr_dias_desde_ultimo_acesso           400 non-null    int64
 6   nr_atividades_sinalizadas             400 non-null    int64
 7   nr_atividades_mapeadas                400 non-null    int64
 8   nr_discussoes_forum_postadas          400 non-null    int64
 9   nr_questionarios_abandonados          400 non-null    int64
 10  nr_questionarios_finalizados          400 non-null    int64
 11  vl_medio_tempo_questionario           111 non-null    float64
 12  vl_medio_tempo_questionario_avaliado  107 non-null    float64
 13  vl_desempenho_questionario            27 non-null     float64
 14  nr_intervalos_uso                     209 non-null    float64
 15  nr_dias_uso                           400 non-null    int64
 16  vl_medio_atividade_diaria             209 non-null    float64
 17  vl_engajamento_usuario_por_intervalo  29 non-null     float64
 18  vl_engajamento_usuario_intradia       29 non-null     float64
 19  nr_interacoes_usuario                 400 non-null    int64
 20  nr_dias_engajamento_discussao         400 non-null    int64
 21  nr_dias_engajamento_questionario      400 non-null    int64
 22  nr_engajamento_discussao              400 non-null    int64
 23  nr_engajamento_questionario           400 non-null    int64
 24  nr_questoes_respondidas               400 non-null    int64
 25  nr_questoes_corretas                  400 non-null    int64
 26  nr_questoes_erradas                   400 non-null    int64
 27  nr_questoes_parciais                  400 non-null    int64
 28  vl_desempenho_usuario                 113 non-null    float64
 29  vl_media_questoes_por_dia             61 non-null     float64
 30  vl_engajamento_notas                  61 non-null     float64
 31  nr_itens_avaliados                    400 non-null    int64
 32  nr_itens_nao_respondidos              400 non-null    int64
 33  vl_media_notas                        113 non-null    float64
 34  nr_submissoes_codigo                  400 non-null    int64
 35  vl_media_submissoes_codigo            4 non-null      float64
 36  vl_submissoes_por_dias_ativos         8 non-null      float64
dtypes: float64(13), int64(23), object(1)
memory usage: 115.8+ KB
None

## describe

In [4]:
print(df_trn.describe())

       Unnamed: 0  ts_primeiro_acesso  ts_ultimo_acesso  \
count  400.000000        4.000000e+02      4.000000e+02
mean   248.027500        8.647958e+08      8.664560e+08
std    140.580382        8.445285e+08      8.461345e+08
min      1.000000        0.000000e+00      0.000000e+00
25%    131.500000        0.000000e+00      0.000000e+00
50%    245.500000        1.661414e+09      1.666093e+09
75%    367.250000        1.692747e+09      1.693434e+09
max    499.000000        1.694097e+09      1.694471e+09

       nr_dias_desde_primeiro_acesso  nr_dias_desde_ultimo_acesso  \
count                     400.000000                   400.000000
mean                     9602.667500                  9583.465000
std                      9774.754241                  9793.330251
min                         4.000000                     0.000000
25%                        20.000000                    12.000000
50%                       382.500000                   328.000000
75%                     19612.000000                 19612.000000
max                     19612.000000                 19612.000000

       nr_atividades_sinalizadas  nr_atividades_mapeadas  \
count                  400.00000              400.000000
mean                     0.17750                0.947500
std                      1.22464                5.036184
min                      0.00000                0.000000
25%                      0.00000                0.000000
50%                      0.00000                0.000000
75%                      0.00000                0.000000
max                     11.00000               48.000000

       nr_discussoes_forum_postadas  nr_questionarios_abandonados  \
count                    400.000000                    400.000000
mean                       0.345000                      0.035000
std                        2.840095                      0.271956
min                        0.000000                      0.000000
25%                        0.000000                      0.000000
50%                        0.000000                      0.000000
75%                        0.000000                      0.000000
max                       39.000000                      3.000000

       nr_questionarios_finalizados  ...  nr_questoes_parciais  \
count                    400.000000  ...            400.000000
mean                       1.445000  ...              0.257500
std                        4.569922  ...              1.024117
min                        0.000000  ...              0.000000
25%                        0.000000  ...              0.000000
50%                        0.000000  ...              0.000000
75%                        1.000000  ...              0.000000
max                       27.000000  ...              9.000000

       vl_desempenho_usuario  vl_media_questoes_por_dia  vl_engajamento_notas  \
count             113.000000                  61.000000             61.000000
mean                0.876987                   0.709287              0.438528
std                 0.256726                   0.883716              0.383358
min                 0.000000                   0.012800              0.008500
25%                 0.919434                   0.209200              0.117200
50%                 1.000000                   0.500000              0.312500
75%                 1.000000                   0.928600              0.666700
max                 1.000000                   5.250000              1.333300

       nr_itens_avaliados  nr_itens_nao_respondidos  vl_media_notas  \
count          400.000000                  400.0000      113.000000
mean             2.407500                   22.2125        0.875059
std              7.610272                   60.1802        0.253001
min              0.000000                    0.0000        0.000000
25%              0.000000                    0.0000        0.919389
50%              0.000000                    0.0000        1.000000
75%              1.000000                   47.2500        1.000000
max             50.000000                  716.0000        1.000000

       nr_submissoes_codigo  vl_media_submissoes_codigo  \
count            400.000000                      4.0000
mean               0.535000                      6.7143
std                4.720645                      0.0000
min                0.000000                      6.7143
25%                0.000000                      6.7143
50%                0.000000                      6.7143
75%                0.000000                      6.7143
max               47.000000                      6.7143

       vl_submissoes_por_dias_ativos
count                       8.000000
mean                       11.083350
std                         4.914363
min                         6.000000
25%                         6.750000
50%                        11.333350
75%                        15.666700
max                        15.666700

[8 rows x 36 columns]

## columns

In [5]:
print(df_trn.columns)

Index(['Unnamed: 0', 'ds_cidade_usuario', 'ts_primeiro_acesso',
       'ts_ultimo_acesso', 'nr_dias_desde_primeiro_acesso',
       'nr_dias_desde_ultimo_acesso', 'nr_atividades_sinalizadas',
       'nr_atividades_mapeadas', 'nr_discussoes_forum_postadas',
       'nr_questionarios_abandonados', 'nr_questionarios_finalizados',
       'vl_medio_tempo_questionario', 'vl_medio_tempo_questionario_avaliado',
       'vl_desempenho_questionario', 'nr_intervalos_uso', 'nr_dias_uso',
       'vl_medio_atividade_diaria', 'vl_engajamento_usuario_por_intervalo',
       'vl_engajamento_usuario_intradia', 'nr_interacoes_usuario',
       'nr_dias_engajamento_discussao', 'nr_dias_engajamento_questionario',
       'nr_engajamento_discussao', 'nr_engajamento_questionario',
       'nr_questoes_respondidas', 'nr_questoes_corretas',
       'nr_questoes_erradas', 'nr_questoes_parciais', 'vl_desempenho_usuario',
       'vl_media_questoes_por_dia', 'vl_engajamento_notas',
       'nr_itens_avaliados', 'nr_itens_nao_respondidos', 'vl_media_notas',
       'nr_submissoes_codigo', 'vl_media_submissoes_codigo',
       'vl_submissoes_por_dias_ativos'],
      dtype='object')

### Teste

In [6]:
print(df_trn.columns)

Index(['Unnamed: 0', 'ds_cidade_usuario', 'ts_primeiro_acesso',
       'ts_ultimo_acesso', 'nr_dias_desde_primeiro_acesso',
       'nr_dias_desde_ultimo_acesso', 'nr_atividades_sinalizadas',
       'nr_atividades_mapeadas', 'nr_discussoes_forum_postadas',
       'nr_questionarios_abandonados', 'nr_questionarios_finalizados',
       'vl_medio_tempo_questionario', 'vl_medio_tempo_questionario_avaliado',
       'vl_desempenho_questionario', 'nr_intervalos_uso', 'nr_dias_uso',
       'vl_medio_atividade_diaria', 'vl_engajamento_usuario_por_intervalo',
       'vl_engajamento_usuario_intradia', 'nr_interacoes_usuario',
       'nr_dias_engajamento_discussao', 'nr_dias_engajamento_questionario',
       'nr_engajamento_discussao', 'nr_engajamento_questionario',
       'nr_questoes_respondidas', 'nr_questoes_corretas',
       'nr_questoes_erradas', 'nr_questoes_parciais', 'vl_desempenho_usuario',
       'vl_media_questoes_por_dia', 'vl_engajamento_notas',
       'nr_itens_avaliados', 'nr_itens_nao_respondidos', 'vl_media_notas',
       'nr_submissoes_codigo', 'vl_media_submissoes_codigo',
       'vl_submissoes_por_dias_ativos'],
      dtype='object')

In [7]:
df_tst

,Unnamed: 0,ds_cidade_usuario,ts_primeiro_acesso,ts_ultimo_acesso,nr_dias_desde_primeiro_acesso,nr_dias_desde_ultimo_acesso,nr_atividades_sinalizadas,nr_atividades_mapeadas,nr_discussoes_forum_postadas,nr_questionarios_abandonados,...,nr_questoes_parciais,vl_desempenho_usuario,vl_media_questoes_por_dia,vl_engajamento_notas,nr_itens_avaliados,nr_itens_nao_respondidos,vl_media_notas,nr_submissoes_codigo,vl_media_submissoes_codigo,vl_submissoes_por_dias_ativos
0,361,Campinas,1693227920,1693228016,14,14,0,0,0,0,...,0,NaN,NaN,NaN,0,0,NaN,0,NaN,NaN
1,73,Holambra,1661542019,1662149939,381,374,0,14,0,0,...,0,0.133333,0.3061,0.1633,15,144,0.133333,0,NaN,NaN
2,374,Campinas,1693578285,1694298462,10,2,0,0,0,0,...,1,0.986014,0.8571,0.5714,6,57,0.984849,0,NaN,NaN
3,155,Campinas,1690827091,1690827413,42,42,0,0,0,0,...,0,NaN,NaN,NaN,0,0,NaN,0,NaN,NaN
4,104,Campinas,0,0,19612,19612,0,0,0,0,...,0,NaN,NaN,NaN,0,0,NaN,0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,347,NaN,1690662696,1690662696,44,44,0,0,0,0,...,0,NaN,NaN,NaN,0,0,NaN,0,NaN,NaN
96,86,NaN,1693428019,1694470591,12,0,0,0,0,0,...,0,1.000000,0.6667,0.6667,2,61,1.000000,0,NaN,NaN
97,75,Campinas,0,0,19612,19612,0,0,0,0,...,0,NaN,NaN,NaN,0,0,NaN,0,NaN,NaN
98,438,Campinas,0,0,19612,19612,0,0,0,0,...,0,NaN,NaN,NaN,0,0,NaN,0,NaN,NaN
99,15,Campinas,0,0,19612,19612,0,0,0,0,...,0,NaN,NaN,NaN,0,0,NaN,0,NaN,NaN

# Removendo colunas não relevantes

In [8]:
df_trn = df_trn.loc[:, ~df_trn.columns.str.contains('^Unnamed')]
df_tst = df_tst.loc[:, ~df_tst.columns.str.contains('^Unnamed')]

In [9]:
limite_nulos = len(df_trn) * 0.2
df_trn = df_trn.dropna(thresh=limite_nulos, axis=1)

limite_nulos = len(df_tst) * 0.2
df_tst = df_tst.dropna(thresh=limite_nulos, axis=1)

# Convertendo timeStamps

In [10]:
df_trn['ts_primeiro_acesso'] = pd.to_datetime(df_trn['ts_primeiro_acesso'], unit='s', errors='coerce')
df_trn['ts_ultimo_acesso'] = pd.to_datetime(df_trn['ts_ultimo_acesso'], unit='s', errors='coerce')

df_tst['ts_primeiro_acesso'] = pd.to_datetime(df_tst['ts_primeiro_acesso'], unit='s', errors='coerce')
df_tst['ts_ultimo_acesso'] = pd.to_datetime(df_tst['ts_ultimo_acesso'], unit='s', errors='coerce')

In [11]:
df_trn = df_trn.rename(columns={
    'ts_primeiro_acesso': 'dt_primeiro_acesso',
    'ts_ultimo_acesso': 'dt_ultimo_acesso'
})

df_tst = df_tst.rename(columns={
    'ts_primeiro_acesso': 'dt_primeiro_acesso',
    'ts_ultimo_acesso': 'dt_ultimo_acesso'
})

# Tratando valores faltantes

In [12]:
print(df_trn.isnull().sum())

ds_cidade_usuario                        54
dt_primeiro_acesso                        0
dt_ultimo_acesso                          0
nr_dias_desde_primeiro_acesso             0
nr_dias_desde_ultimo_acesso               0
nr_atividades_sinalizadas                 0
nr_atividades_mapeadas                    0
nr_discussoes_forum_postadas              0
nr_questionarios_abandonados              0
nr_questionarios_finalizados              0
vl_medio_tempo_questionario             289
vl_medio_tempo_questionario_avaliado    293
nr_intervalos_uso                       191
nr_dias_uso                               0
vl_medio_atividade_diaria               191
nr_interacoes_usuario                     0
nr_dias_engajamento_discussao             0
nr_dias_engajamento_questionario          0
nr_engajamento_discussao                  0
nr_engajamento_questionario               0
nr_questoes_respondidas                   0
nr_questoes_corretas                      0
nr_questoes_erradas                       0
nr_questoes_parciais                      0
vl_desempenho_usuario                   287
nr_itens_avaliados                        0
nr_itens_nao_respondidos                  0
vl_media_notas                          287
nr_submissoes_codigo                      0
dtype: int64

In [13]:
df_trn = df_trn.fillna(0)
df_tst = df_tst.fillna(0)

# Removendo dados Duplicados

In [14]:
print(df_trn.duplicated().sum())

307

In [15]:
print(f"Antes: {len(df_trn)} linhas")

print(f"Antes: {len(df_tst)} linhas")

Antes: 400 linhas
Antes: 100 linhas

In [16]:
df_trn = df_trn.drop_duplicates(keep='last')

df_tst = df_tst.drop_duplicates(keep='last')

In [17]:
print(f"Depois: {len(df_trn)} linhas")

print(f"Depois: {len(df_tst)} linhas")

Depois: 93 linhas
Depois: 38 linhas

# Ajustando data invalidadas

In [18]:
df_trn = df_trn[df_trn['dt_primeiro_acesso'].dt.year != 1970]
df_trn = df_trn[df_trn['dt_ultimo_acesso'].dt.year != 1970]

df_tst = df_tst[df_tst['dt_primeiro_acesso'].dt.year != 1970]
df_tst = df_tst[df_tst['dt_ultimo_acesso'].dt.year != 1970]

# Supondo que alunos que não entram a mais de 90 dias fora do periodo de ferias abandonaram

In [19]:
meses_ferias = [1, 2, 7, 12]

def verificar_abandono(row):
    ultimo_acesso = row['dt_ultimo_acesso']
    dias_sem_acesso = row['nr_dias_desde_ultimo_acesso']

    if ultimo_acesso.month in meses_ferias:
        return 0
    elif dias_sem_acesso > 90:
        return 1
    else:
        return 0
    
df_trn['abandono'] = df_trn.apply(verificar_abandono, axis=1)
df_tst['abandono'] = df_tst.apply(verificar_abandono, axis=1)

# removendo colunas não mais nescessarias

In [20]:
colunas_remover = ['dt_primeiro_acesso', 'dt_ultimo_acesso', 'ds_cidade_usuario']
df_trn = df_trn.drop(columns=colunas_remover)
df_tst = df_tst.drop(columns=colunas_remover)

# Revisando dados

In [21]:
df_trn

,nr_dias_desde_primeiro_acesso,nr_dias_desde_ultimo_acesso,nr_atividades_sinalizadas,nr_atividades_mapeadas,nr_discussoes_forum_postadas,nr_questionarios_abandonados,nr_questionarios_finalizados,vl_medio_tempo_questionario,vl_medio_tempo_questionario_avaliado,nr_intervalos_uso,...,nr_questoes_respondidas,nr_questoes_corretas,nr_questoes_erradas,nr_questoes_parciais,vl_desempenho_usuario,nr_itens_avaliados,nr_itens_nao_respondidos,vl_media_notas,nr_submissoes_codigo,abandono
3,20,6,0,4,0,0,1,111.0,111.0,14.0,...,44,1,0,0,1.000000,1,62,1.000000,0,0
7,19,18,0,0,0,0,0,0.0,0.0,1.0,...,0,0,0,0,0.000000,0,0,0.000000,0,0
26,34,34,0,0,0,0,1,49.0,49.0,0.0,...,44,1,0,0,1.000000,1,62,1.000000,0,0
29,20,5,0,0,0,0,2,1033.5,1033.5,15.0,...,58,40,16,0,1.000000,5,58,1.000000,0,0
31,20,20,0,0,0,0,0,0.0,0.0,0.0,...,0,0,0,0,0.000000,0,0,0.000000,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
391,220,12,0,12,0,0,0,0.0,0.0,208.0,...,0,0,0,0,0.000000,0,90,0.000000,0,0
392,12,1,0,0,0,0,2,1454.5,1454.5,11.0,...,59,39,18,0,1.000000,1,62,1.000000,0,0
394,4,0,0,0,0,0,4,869.5,869.5,4.0,...,64,55,5,1,0.991754,21,42,0.990380,6,0
395,305,305,0,0,0,0,1,2629.0,2629.0,273.0,...,37,14,10,0,0.767437,2,43,0.689917,0,1
397,33,33,0,0,0,0,0,0.0,0.0,0.0,...,0,0,0,0,0.000000,0,0,0.000000,0,0

In [22]:
print(df_trn.info())

<class 'pandas.core.frame.DataFrame'>
Index: 90 entries, 3 to 397
Data columns (total 27 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   nr_dias_desde_primeiro_acesso         90 non-null     int64
 1   nr_dias_desde_ultimo_acesso           90 non-null     int64
 2   nr_atividades_sinalizadas             90 non-null     int64
 3   nr_atividades_mapeadas                90 non-null     int64
 4   nr_discussoes_forum_postadas          90 non-null     int64
 5   nr_questionarios_abandonados          90 non-null     int64
 6   nr_questionarios_finalizados          90 non-null     int64
 7   vl_medio_tempo_questionario           90 non-null     float64
 8   vl_medio_tempo_questionario_avaliado  90 non-null     float64
 9   nr_intervalos_uso                     90 non-null     float64
 10  nr_dias_uso                           90 non-null     int64
 11  vl_medio_atividade_diaria             90 non-null     float64
 12  nr_interacoes_usuario                 90 non-null     int64
 13  nr_dias_engajamento_discussao         90 non-null     int64
 14  nr_dias_engajamento_questionario      90 non-null     int64
 15  nr_engajamento_discussao              90 non-null     int64
 16  nr_engajamento_questionario           90 non-null     int64
 17  nr_questoes_respondidas               90 non-null     int64
 18  nr_questoes_corretas                  90 non-null     int64
 19  nr_questoes_erradas                   90 non-null     int64
 20  nr_questoes_parciais                  90 non-null     int64
 21  vl_desempenho_usuario                 90 non-null     float64
 22  nr_itens_avaliados                    90 non-null     int64
 23  nr_itens_nao_respondidos              90 non-null     int64
 24  vl_media_notas                        90 non-null     float64
 25  nr_submissoes_codigo                  90 non-null     int64
 26  abandono                              90 non-null     int64
dtypes: float64(6), int64(21)
memory usage: 19.7 KB
None

In [23]:
df_trn

,nr_dias_desde_primeiro_acesso,nr_dias_desde_ultimo_acesso,nr_atividades_sinalizadas,nr_atividades_mapeadas,nr_discussoes_forum_postadas,nr_questionarios_abandonados,nr_questionarios_finalizados,vl_medio_tempo_questionario,vl_medio_tempo_questionario_avaliado,nr_intervalos_uso,...,nr_questoes_respondidas,nr_questoes_corretas,nr_questoes_erradas,nr_questoes_parciais,vl_desempenho_usuario,nr_itens_avaliados,nr_itens_nao_respondidos,vl_media_notas,nr_submissoes_codigo,abandono
3,20,6,0,4,0,0,1,111.0,111.0,14.0,...,44,1,0,0,1.000000,1,62,1.000000,0,0
7,19,18,0,0,0,0,0,0.0,0.0,1.0,...,0,0,0,0,0.000000,0,0,0.000000,0,0
26,34,34,0,0,0,0,1,49.0,49.0,0.0,...,44,1,0,0,1.000000,1,62,1.000000,0,0
29,20,5,0,0,0,0,2,1033.5,1033.5,15.0,...,58,40,16,0,1.000000,5,58,1.000000,0,0
31,20,20,0,0,0,0,0,0.0,0.0,0.0,...,0,0,0,0,0.000000,0,0,0.000000,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
391,220,12,0,12,0,0,0,0.0,0.0,208.0,...,0,0,0,0,0.000000,0,90,0.000000,0,0
392,12,1,0,0,0,0,2,1454.5,1454.5,11.0,...,59,39,18,0,1.000000,1,62,1.000000,0,0
394,4,0,0,0,0,0,4,869.5,869.5,4.0,...,64,55,5,1,0.991754,21,42,0.990380,6,0
395,305,305,0,0,0,0,1,2629.0,2629.0,273.0,...,37,14,10,0,0.767437,2,43,0.689917,0,1
397,33,33,0,0,0,0,0,0.0,0.0,0.0,...,0,0,0,0,0.000000,0,0,0.000000,0,0

In [24]:
print(df_trn.describe())

       nr_dias_desde_primeiro_acesso  nr_dias_desde_ultimo_acesso  \
count                      90.000000                    90.000000
mean                       81.466667                    45.233333
std                       118.896348                    85.249673
min                         4.000000                     0.000000
25%                        12.000000                     6.000000
50%                        21.000000                    13.000000
75%                        54.000000                    26.750000
max                       390.000000                   353.000000

       nr_atividades_sinalizadas  nr_atividades_mapeadas  \
count                  90.000000               90.000000
mean                    0.188889                1.855556
std                     1.271065                7.191695
min                     0.000000                0.000000
25%                     0.000000                0.000000
50%                     0.000000                0.000000
75%                     0.000000                0.000000
max                    11.000000               48.000000

       nr_discussoes_forum_postadas  nr_questionarios_abandonados  \
count                     90.000000                     90.000000
mean                       0.666667                      0.066667
std                        4.232034                      0.390908
min                        0.000000                      0.000000
25%                        0.000000                      0.000000
50%                        0.000000                      0.000000
75%                        0.000000                      0.000000
max                       39.000000                      3.000000

       nr_questionarios_finalizados  vl_medio_tempo_questionario  \
count                     90.000000                    90.000000
mean                       1.944444                 12971.791491
std                        4.596924                 54674.854798
min                        0.000000                     0.000000
25%                        0.000000                     0.000000
50%                        0.000000                     0.000000
75%                        2.000000                   942.500000
max                       27.000000                432769.500000

       vl_medio_tempo_questionario_avaliado  nr_intervalos_uso  ...  \
count                             90.000000          90.000000  ...
mean                           15937.318797          47.744444  ...
std                            65902.027204         100.093502  ...
min                                0.000000           0.000000  ...
25%                                0.000000           0.000000  ...
50%                                0.000000           4.000000  ...
75%                              855.625000          26.500000  ...
max                           432769.500000         390.000000  ...

       nr_questoes_respondidas  nr_questoes_corretas  nr_questoes_erradas  \
count                90.000000             90.000000            90.000000
mean                 31.988889             22.788889             2.866667
std                  57.058120             47.422911             5.092846
min                   0.000000              0.000000             0.000000
25%                   0.000000              0.000000             0.000000
50%                   0.000000              0.500000             0.000000
75%                  58.000000             44.750000             4.750000
max                 345.000000            290.000000            21.000000

       nr_questoes_parciais  vl_desempenho_usuario  nr_itens_avaliados  \
count             90.000000              90.000000           90.000000
mean               0.377778               0.432633            3.233333
std                1.137490               0.483156            7.802405
min                0.000000               0.000000            0.000000
25%                0.000000               0.000000            0.000000
50%                0.000000               0.000000            0.000000
75%                0.000000               1.000000            2.000000
max                9.000000               1.000000           50.000000

       nr_itens_nao_respondidos  vl_media_notas  nr_submissoes_codigo  \
count                 90.000000       90.000000             90.000000
mean                  41.022222        0.431048              0.733333
std                   85.029668        0.481429              5.063196
min                    0.000000        0.000000              0.000000
25%                    0.000000        0.000000              0.000000
50%                    2.000000        0.000000              0.000000
75%                   61.000000        1.000000              0.000000
max                  716.000000        1.000000             47.000000

        abandono
count  90.000000
mean    0.077778
std     0.269322
min     0.000000
25%     0.000000
50%     0.000000
75%     0.000000
max     1.000000

[8 rows x 27 columns]

In [25]:
print(df_trn.dtypes)

nr_dias_desde_primeiro_acesso             int64
nr_dias_desde_ultimo_acesso               int64
nr_atividades_sinalizadas                 int64
nr_atividades_mapeadas                    int64
nr_discussoes_forum_postadas              int64
nr_questionarios_abandonados              int64
nr_questionarios_finalizados              int64
vl_medio_tempo_questionario             float64
vl_medio_tempo_questionario_avaliado    float64
nr_intervalos_uso                       float64
nr_dias_uso                               int64
vl_medio_atividade_diaria               float64
nr_interacoes_usuario                     int64
nr_dias_engajamento_discussao             int64
nr_dias_engajamento_questionario          int64
nr_engajamento_discussao                  int64
nr_engajamento_questionario               int64
nr_questoes_respondidas                   int64
nr_questoes_corretas                      int64
nr_questoes_erradas                       int64
nr_questoes_parciais                      int64
vl_desempenho_usuario                   float64
nr_itens_avaliados                        int64
nr_itens_nao_respondidos                  int64
vl_media_notas                          float64
nr_submissoes_codigo                      int64
abandono                                  int64
dtype: object

In [26]:
print(df_trn.isnull().sum())

nr_dias_desde_primeiro_acesso           0
nr_dias_desde_ultimo_acesso             0
nr_atividades_sinalizadas               0
nr_atividades_mapeadas                  0
nr_discussoes_forum_postadas            0
nr_questionarios_abandonados            0
nr_questionarios_finalizados            0
vl_medio_tempo_questionario             0
vl_medio_tempo_questionario_avaliado    0
nr_intervalos_uso                       0
nr_dias_uso                             0
vl_medio_atividade_diaria               0
nr_interacoes_usuario                   0
nr_dias_engajamento_discussao           0
nr_dias_engajamento_questionario        0
nr_engajamento_discussao                0
nr_engajamento_questionario             0
nr_questoes_respondidas                 0
nr_questoes_corretas                    0
nr_questoes_erradas                     0
nr_questoes_parciais                    0
vl_desempenho_usuario                   0
nr_itens_avaliados                      0
nr_itens_nao_respondidos                0
vl_media_notas                          0
nr_submissoes_codigo                    0
abandono                                0
dtype: int64

# Salvando Copia dados limpos

In [27]:
df_trn.to_csv('../data/gui_dados_limpos_treino.csv', index=False)
df_tst.to_csv('../data/gui_dados_limpos_teste.csv', index=False)